#pragma config(UART_Usage, UART2, uartUserControl, baudRate38400, IOPins, None, None)
#pragma config(Sensor, dgtl10, green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, red,            sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ANALOG_COUNT 8
#define ANALOG_START 0

#define DIGITAL_COUNT 12
#define DIGITAL_START dgtl1

#define MOTOR_COUNT 10
#define MOTOR_START 0

#define CMD_WRITE 0
#define CMD_COMMIT 10
#define CMD_WRITE_DIGITAL 1
#define CMD_WRITE_ANALOG 2
#define CMD_WRITE_MOTOR 3

int cmdId = -1;
int typeId = -1;
int pinId = -1;
int writeVal = -1;

long errorTime = 0;
long lastFlash = 0;

long sensorValues[48] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
													0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
													0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
													0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
long motors[10] = { 0, 0, 0, 0, 0, 0, 0 ,0 , 0, 0 };

void writeChar(char c)
{
	sendChar(uartTwo, c);
	while (!bXmitComplete(uartOne));
}

void writeChars(char* c)
{
	string s;
	stringFromChars(s, c);

	for (int i = 0; i < strlen(s); i ++)
		writeChar(stringGetChar(s, i));
}

void writeLine(char* c)
{
	writeChars(c);
	writeChar('\n');
}

void writeSensorUpdate(char* name, long* arr, int s, int c)
{
	writeChars(name);
	writeChars("Update:");
	for (int i = s; i < s + c; i ++)
		writeChar(arr[i]);
	writeLine(";");
}

task SendSensorValues()
{
	while (true)
	{
		for (int i = 0; i < 48; i ++)
			sensorValues[i] = SensorValue[i];
		writeSensorUpdate("Analog", &sensorValues[0], ANALOG_START, ANALOG_COUNT);
		writeSensorUpdate("Digital", &sensorValues[0], DIGITAL_START, DIGITAL_COUNT);
		for (int i = 0; i < 10; i ++)
			motors[i] = motor[i];
		writeSensorUpdate("Motor", motors, MOTOR_START, MOTOR_COUNT);
		wait1Msec(20);
	}
}

void commitWrite()
{
	switch (typeId)
	{
	case CMD_WRITE_DIGITAL:
		SensorValue[dgtl1 + pinId] = writeVal;
		break;
	case CMD_WRITE_ANALOG:
		SensorValue[pinId] = writeVal;
		break;
	case CMD_WRITE_MOTOR:
		motor[pinId] = writeVal;
	}
}

void commandIncrement(byte val)
{
	if (cmdId == -1)
	{
		switch (val)
		{
		case CMD_WRITE:
			cmdId = val;
			typeId = -1;
			pinId = -1;
			writeVal = -1;
			break;
		default:
			cmdId = -1;
			SensorValue[red] = 1;
			errorTime = nSysTime;
		}
	} else
	{
		switch (cmdId)
		{
		case CMD_WRITE:
			if (typeId == -1)
				typeId = val;
			else if (pinId == -1)
				pinId = val;
			else if (writeVal == -1)
				writeVal = val;
			else if (val == CMD_COMMIT)
			{
				commitWrite();
				cmdId = -1;

				if (typeId == CMD_WRITE_DIGITAL && pinId == 10)
					lastFlash = nSysTime;
			}
			break;
		default:
			cmdId = -1;
			SensorValue[red] = 1;
			errorTime = nSysTime;
		}
	}

	if (nSysTime - errorTime > 10000)
		SensorValue[red] = 0;

	if (nSysTime - lastFlash > 1000 && nSysTime - errorTime > 1000)
	{
		cmdId = -1;
		SensorValue[red] = 1;
		errorTime = nSysTime;
	}
}

task WaitForCommands()
{
	while (true)
	{
		char rx = getChar(uartTwo);
		if (rx != 255)
			commandIncrement(rx);
	}
}

task main()
{
	while (getChar(uartTwo) != -1)
	{}
	lastFlash = nSysTime;

	startTask(SendSensorValues);
	startTask(WaitForCommands);

	/*
	char rx = getChar(uartTwo);

		if (rx != 255)
		{
			writeLine("Received");
			writeLine("Received2");
			writeDebugStreamLine("%d", rx);
		}
	*/

	while (true)
	{
		wait1Msec(500);
		SensorValue[green] = 1 - SensorValue[green];
	}
}
